// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: pkg/api/proto/hcivcls.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HCIVclsServiceClient is the client API for HCIVclsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HCIVclsServiceClient interface {
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetDegradation(ctx context.Context, in *DegradationRequest, opts ...grpc.CallOption) (*DegradationResponse, error)
	EvaluateHA(ctx context.Context, in *EvaluateHARequest, opts ...grpc.CallOption) (*EvaluateHAResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*GetPlanResponse, error)
	SweeperStatus(ctx context.Context, in *SweeperStatusRequest, opts ...grpc.CallOption) (*SweeperStatusResponse, error)
	QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (*QueryAuditResponse, error)
}

type hCIVclsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHCIVclsServiceClient(cc grpc.ClientConnInterface) HCIVclsServiceClient {
	return &hCIVclsServiceClient{cc}
}

func (c *hCIVclsServiceClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/hcivcls.HCIVclsService/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hCIVclsServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/hcivcls.HCIVclsService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hCIVclsServiceClient) GetDegradation(ctx context.Context, in *DegradationRequest, opts ...grpc.CallOption) (*DegradationResponse, error) {
	out := new(DegradationResponse)
	err := c.cc.Invoke(ctx, "/hcivcls.HCIVclsService/GetDegradation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hCIVclsServiceClient) EvaluateHA(ctx context.Context, in *EvaluateHARequest, opts ...grpc.CallOption) (*EvaluateHAResponse, error) {
	out := new(EvaluateHAResponse)
	err := c.cc.Invoke(ctx, "/hcivcls.HCIVclsService/EvaluateHA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hCIVclsServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, "/hcivcls.HCIVclsService/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hCIVclsServiceClient) GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*GetPlanResponse, error) {
	out := new(GetPlanResponse)
	err := c.cc.Invoke(ctx, "/hcivcls.HCIVclsService/GetPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hCIVclsServiceClient) SweeperStatus(ctx context.Context, in *SweeperStatusRequest, opts ...grpc.CallOption) (*SweeperStatusResponse, error) {
	out := new(SweeperStatusResponse)
	err := c.cc.Invoke(ctx, "/hcivcls.HCIVclsService/SweeperStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hCIVclsServiceClient) QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (*QueryAuditResponse, error) {
	out := new(QueryAuditResponse)
	err := c.cc.Invoke(ctx, "/hcivcls.HCIVclsService/QueryAudit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HCIVclsServiceServer is the server API for HCIVclsService service.
// All implementations must embed UnimplementedHCIVclsServiceServer
// for forward compatibility
type HCIVclsServiceServer interface {
	GetVersion(context.Context, *VersionRequest) (*VersionResponse, error)
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	GetDegradation(context.Context, *DegradationRequest) (*DegradationResponse, error)
	EvaluateHA(context.Context, *EvaluateHARequest) (*EvaluateHAResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	GetPlan(context.Context, *GetPlanRequest) (*GetPlanResponse, error)
	SweeperStatus(context.Context, *SweeperStatusRequest) (*SweeperStatusResponse, error)
	QueryAudit(context.Context, *QueryAuditRequest) (*QueryAuditResponse, error)
	mustEmbedUnimplementedHCIVclsServiceServer()
}

// UnimplementedHCIVclsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHCIVclsServiceServer struct {
}

func (UnimplementedHCIVclsServiceServer) GetVersion(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedHCIVclsServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedHCIVclsServiceServer) GetDegradation(context.Context, *DegradationRequest) (*DegradationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDegradation not implemented")
}
func (UnimplementedHCIVclsServiceServer) EvaluateHA(context.Context, *EvaluateHARequest) (*EvaluateHAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateHA not implemented")
}
func (UnimplementedHCIVclsServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedHCIVclsServiceServer) GetPlan(context.Context, *GetPlanRequest) (*GetPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlan not implemented")
}
func (UnimplementedHCIVclsServiceServer) SweeperStatus(context.Context, *SweeperStatusRequest) (*SweeperStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SweeperStatus not implemented")
}
func (UnimplementedHCIVclsServiceServer) QueryAudit(context.Context, *QueryAuditRequest) (*QueryAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAudit not implemented")
}
func (UnimplementedHCIVclsServiceServer) mustEmbedUnimplementedHCIVclsServiceServer() {}

// UnsafeHCIVclsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HCIVclsServiceServer will
// result in compilation errors.
type UnsafeHCIVclsServiceServer interface {
	mustEmbedUnimplementedHCIVclsServiceServer()
}

func RegisterHCIVclsServiceServer(s grpc.ServiceRegistrar, srv HCIVclsServiceServer) {
	s.RegisterService(&HCIVclsService_ServiceDesc, srv)
}

func _HCIVclsService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HCIVclsServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hcivcls.HCIVclsService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HCIVclsServiceServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HCIVclsService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HCIVclsServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hcivcls.HCIVclsService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HCIVclsServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HCIVclsService_GetDegradation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DegradationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HCIVclsServiceServer).GetDegradation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hcivcls.HCIVclsService/GetDegradation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HCIVclsServiceServer).GetDegradation(ctx, req.(*DegradationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HCIVclsService_EvaluateHA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateHARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HCIVclsServiceServer).EvaluateHA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hcivcls.HCIVclsService/EvaluateHA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HCIVclsServiceServer).EvaluateHA(ctx, req.(*EvaluateHARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HCIVclsService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HCIVclsServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hcivcls.HCIVclsService/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HCIVclsServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HCIVclsService_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HCIVclsServiceServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hcivcls.HCIVclsService/GetPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HCIVclsServiceServer).GetPlan(ctx, req.(*GetPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HCIVclsService_SweeperStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SweeperStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HCIVclsServiceServer).SweeperStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hcivcls.HCIVclsService/SweeperStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HCIVclsServiceServer).SweeperStatus(ctx, req.(*SweeperStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HCIVclsService_QueryAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HCIVclsServiceServer).QueryAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hcivcls.HCIVclsService/QueryAudit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HCIVclsServiceServer).QueryAudit(ctx, req.(*QueryAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HCIVclsService_ServiceDesc is the grpc.ServiceDesc for HCIVclsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HCIVclsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hcivcls.HCIVclsService",
	HandlerType: (*HCIVclsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _HCIVclsService_GetVersion_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _HCIVclsService_GetStatus_Handler,
		},
		{
			MethodName: "GetDegradation",
			Handler:    _HCIVclsService_GetDegradation_Handler,
		},
		{
			MethodName: "EvaluateHA",
			Handler:    _HCIVclsService_EvaluateHA_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _HCIVclsService_ListTasks_Handler,
		},
		{
			MethodName: "GetPlan",
			Handler:    _HCIVclsService_GetPlan_Handler,
		},
		{
			MethodName: "SweeperStatus",
			Handler:    _HCIVclsService_SweeperStatus_Handler,
		},
		{
			MethodName: "QueryAudit",
			Handler:    _HCIVclsService_QueryAudit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/hcivcls.proto",
}
