// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pkg/api/proto/hcivcls.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HAService_Evaluate_FullMethodName       = "/hcivcls.HAService/Evaluate"
	HAService_GetActiveTasks_FullMethodName = "/hcivcls.HAService/GetActiveTasks"
)

// HAServiceClient is the client API for HAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HAServiceClient interface {
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	GetActiveTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksResponse, error)
}

type hAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHAServiceClient(cc grpc.ClientConnInterface) HAServiceClient {
	return &hAServiceClient{cc}
}

func (c *hAServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, HAService_Evaluate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hAServiceClient) GetActiveTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksResponse, error) {
	out := new(GetTasksResponse)
	err := c.cc.Invoke(ctx, HAService_GetActiveTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HAServiceServer is the server API for HAService service.
// All implementations must embed UnimplementedHAServiceServer
// for forward compatibility
type HAServiceServer interface {
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	GetActiveTasks(context.Context, *GetTasksRequest) (*GetTasksResponse, error)
	mustEmbedUnimplementedHAServiceServer()
}

// UnimplementedHAServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHAServiceServer struct {
}

func (UnimplementedHAServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedHAServiceServer) GetActiveTasks(context.Context, *GetTasksRequest) (*GetTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveTasks not implemented")
}
func (UnimplementedHAServiceServer) mustEmbedUnimplementedHAServiceServer() {}

// UnsafeHAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HAServiceServer will
// result in compilation errors.
type UnsafeHAServiceServer interface {
	mustEmbedUnimplementedHAServiceServer()
}

func RegisterHAServiceServer(s grpc.ServiceRegistrar, srv HAServiceServer) {
	s.RegisterService(&HAService_ServiceDesc, srv)
}

func _HAService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HAService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HAService_GetActiveTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAServiceServer).GetActiveTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HAService_GetActiveTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAServiceServer).GetActiveTasks(ctx, req.(*GetTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HAService_ServiceDesc is the grpc.ServiceDesc for HAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hcivcls.HAService",
	HandlerType: (*HAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _HAService_Evaluate_Handler,
		},
		{
			MethodName: "GetActiveTasks",
			Handler:    _HAService_GetActiveTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/hcivcls.proto",
}

const (
	FDMService_GetClusterStatus_FullMethodName = "/hcivcls.FDMService/GetClusterStatus"
	FDMService_GetDegradation_FullMethodName   = "/hcivcls.FDMService/GetDegradation"
)

// FDMServiceClient is the client API for FDMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FDMServiceClient interface {
	GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error)
	GetDegradation(ctx context.Context, in *GetDegradationRequest, opts ...grpc.CallOption) (*GetDegradationResponse, error)
}

type fDMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFDMServiceClient(cc grpc.ClientConnInterface) FDMServiceClient {
	return &fDMServiceClient{cc}
}

func (c *fDMServiceClient) GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error) {
	out := new(GetClusterStatusResponse)
	err := c.cc.Invoke(ctx, FDMService_GetClusterStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fDMServiceClient) GetDegradation(ctx context.Context, in *GetDegradationRequest, opts ...grpc.CallOption) (*GetDegradationResponse, error) {
	out := new(GetDegradationResponse)
	err := c.cc.Invoke(ctx, FDMService_GetDegradation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FDMServiceServer is the server API for FDMService service.
// All implementations must embed UnimplementedFDMServiceServer
// for forward compatibility
type FDMServiceServer interface {
	GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error)
	GetDegradation(context.Context, *GetDegradationRequest) (*GetDegradationResponse, error)
	mustEmbedUnimplementedFDMServiceServer()
}

// UnimplementedFDMServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFDMServiceServer struct {
}

func (UnimplementedFDMServiceServer) GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedFDMServiceServer) GetDegradation(context.Context, *GetDegradationRequest) (*GetDegradationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDegradation not implemented")
}
func (UnimplementedFDMServiceServer) mustEmbedUnimplementedFDMServiceServer() {}

// UnsafeFDMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FDMServiceServer will
// result in compilation errors.
type UnsafeFDMServiceServer interface {
	mustEmbedUnimplementedFDMServiceServer()
}

func RegisterFDMServiceServer(s grpc.ServiceRegistrar, srv FDMServiceServer) {
	s.RegisterService(&FDMService_ServiceDesc, srv)
}

func _FDMService_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FDMServiceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FDMService_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FDMServiceServer).GetClusterStatus(ctx, req.(*GetClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FDMService_GetDegradation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDegradationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FDMServiceServer).GetDegradation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FDMService_GetDegradation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FDMServiceServer).GetDegradation(ctx, req.(*GetDegradationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FDMService_ServiceDesc is the grpc.ServiceDesc for FDMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FDMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hcivcls.FDMService",
	HandlerType: (*FDMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterStatus",
			Handler:    _FDMService_GetClusterStatus_Handler,
		},
		{
			MethodName: "GetDegradation",
			Handler:    _FDMService_GetDegradation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/hcivcls.proto",
}

const (
	StatusService_GetFullStatus_FullMethodName = "/hcivcls.StatusService/GetFullStatus"
)

// StatusServiceClient is the client API for StatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatusServiceClient interface {
	GetFullStatus(ctx context.Context, in *GetFullStatusRequest, opts ...grpc.CallOption) (*GetFullStatusResponse, error)
}

type statusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusServiceClient(cc grpc.ClientConnInterface) StatusServiceClient {
	return &statusServiceClient{cc}
}

func (c *statusServiceClient) GetFullStatus(ctx context.Context, in *GetFullStatusRequest, opts ...grpc.CallOption) (*GetFullStatusResponse, error) {
	out := new(GetFullStatusResponse)
	err := c.cc.Invoke(ctx, StatusService_GetFullStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusServiceServer is the server API for StatusService service.
// All implementations must embed UnimplementedStatusServiceServer
// for forward compatibility
type StatusServiceServer interface {
	GetFullStatus(context.Context, *GetFullStatusRequest) (*GetFullStatusResponse, error)
	mustEmbedUnimplementedStatusServiceServer()
}

// UnimplementedStatusServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatusServiceServer struct {
}

func (UnimplementedStatusServiceServer) GetFullStatus(context.Context, *GetFullStatusRequest) (*GetFullStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullStatus not implemented")
}
func (UnimplementedStatusServiceServer) mustEmbedUnimplementedStatusServiceServer() {}

// UnsafeStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusServiceServer will
// result in compilation errors.
type UnsafeStatusServiceServer interface {
	mustEmbedUnimplementedStatusServiceServer()
}

func RegisterStatusServiceServer(s grpc.ServiceRegistrar, srv StatusServiceServer) {
	s.RegisterService(&StatusService_ServiceDesc, srv)
}

func _StatusService_GetFullStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFullStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServiceServer).GetFullStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatusService_GetFullStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServiceServer).GetFullStatus(ctx, req.(*GetFullStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatusService_ServiceDesc is the grpc.ServiceDesc for StatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hcivcls.StatusService",
	HandlerType: (*StatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullStatus",
			Handler:    _StatusService_GetFullStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/hcivcls.proto",
}
